"""Fix user nullables

Revision ID: 62e659909ca8
Revises: b4c298c3c110
Create Date: 2020-07-02 10:17:30.228011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e659909ca8'
down_revision = 'b4c298c3c110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
