"""_id to id

Revision ID: fb61a9628e8f
Revises: 62e659909ca8
Create Date: 2020-07-02 11:45:55.428000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb61a9628e8f'
down_revision = '62e659909ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'productid')
    op.drop_column('user', 'user_id')
    op.add_column('product', sa.Column('id', sa.Integer(), primary_key=True))
    op.add_column('user', sa.Column('id', sa.Integer(), primary_key=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id')
    op.drop_column('product', 'id')
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), primary_key=True))
    op.add_column('product', sa.Column('productid', sa.INTEGER(), primary_key=True))
    # ### end Alembic commands ###
